### PR TITLE
Include dist and lib directories into the repository

### PR DESCRIPTION
**Pull request by agrinko**
Hi @yuku 
I think you shouldn't ignore lib and dist directories with .gitignore and publish them in the repository instead, for the following reasons:
1) `lib/index.js` is specified as the main script in `package.json` - but it's absent in the repo!
2) if somebody wants to download your plugin through NPM, but still has to specify a path to the compiled and minified version, there is no way now. I want to be able to specify "node_modules/textcomplete/dist/textcomplete.min.js" for my Rails bundler or some other tool instead of downloading the dist file manually
3) Actually, without `lib` folder this plugin only works for flow-typed projects. How do we import it into TypeScript projects? Plain JS projects? Publish `lib` folder, and `lib/index.js` will be used by default when you import `textcomplete` module. I checked, it works for me now.

### CODE REVIEW

**Comment by yuku** [comment]
This is intended design. When I included them, many developers send PRs to dist and lib instead of src.

> I want to be able to specify "node_modules/textcomplete/dist/textcomplete.min.js" for my Rails bundler or some other tool instead of downloading the dist file manually

In my understanding, the npm package includes dist and lib directory (so you can access download dist/textcomplete.min.js via [unpkg.com](https://unpkg.com/textcomplete@0.17.1/dist/textcomplete.min.js) which delivers files from npm package not github repository)

> Actually, without lib folder this plugin only works for flow-typed projects. How do we import it into TypeScript projects? Plain JS projects? Publish lib folder, and lib/index.js will be used by default when you import textcomplete module. I checked, it works for me now.

Currently you have to import this as plain JS module.

One good news is that I'm rewriting this package in TypeScript at [yuku/jquery-textcomplete@master](https://github.com/yuku/jquery-textcomplete/tree/master) (note that master is not the default branch now). After I finishes the task, I will

- rename this repository as something like yuku/textcomplete-old and archive it.
- rename yuku/jquery-textcomplete as yuku/textcomplete.

At that time, yuku/textcomplete contains both jquery-textcomplete and textcomplete. It becomes a mono repository.

Do you wonder why I reuse yuku/jquery-textcomplete instead of this repository? That's because yuku/jquery-textcomplete has a lot of ⭐️ than this 😆

**Comment by agrinko** [comment]
@yuku , ok, so why do other libraries and plugins include dist directory into published code?  I cannot include it as a plain JS module:
1. I don't want new global variables.
2. I want code completion in my IDE which needs to know where `Textarea` and `Textcomplete` variables come from.
3. I don't want to download the file manually and include it to the source code. It's 21st century! :) I want to be able to update it with NPM as soon as needed.
3. I want full source code in development, and let my project's code optimization & minification features do the rest; it doesn't work this way if I include minified textcomplete bundle directly

The issue with developers creating PRs to dist folder may be solved in some other way, not related to the source code.
Finally, if you still do not approve my changes, I'll have to keep using my own fork. But at least change the `main` reference in the `package.json` - it's wrong

**Comment by yuku** [comment]
Following screenshot comes from my another project which uses textcomplete. It includes lib and dist directories.

image

**Comment by agrinko** [comment]
@yuku , indeed, you are right. Somehow I didn't have those directories initially, maybe installed it in some wrong way. Now all good, thank you!

**Pull request closed without merging**
